services:
  - type: web
    name: ds-inventory-server
    env: python
    region: oregon
    plan: free
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=all --prefer-binary -r requirements.txt
      python add_name_column.py || echo "Migration script completed"
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-change-this-in-production-render-deployment
      - key: PYTHONPATH
        value: /opt/render/project/src
