services:
  - type: web
    name: ds-inventory-server
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3.11 python3.11-venv
      ln -sf /usr/bin/python3.11 /usr/bin/python
      pip install --upgrade pip setuptools wheel
      pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
